FROM python:3.12-slim
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install python3-pip -y &&  pip install --upgrade pip && pip install -r requirements.txt
COPY main.py .
#  Ваш код здесь #

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 
